create table public.contact_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id),
  name text not null check (length(name) between 1 and 150),
  email text not null check (length(email) between 3 and 254),
  message text not null check (length(message) between 10 and 5000),
  created_at timestamptz not null default now()
);
alter table public.contact_messages enable row level security;
revoke all on public.contact_messages from anon, authenticated;
grant select, insert on public.contact_messages to authenticated;
grant usage on sequence public.contact_messages_id_seq to authenticated;
create policy contact_insert_own on public.contact_messages for insert to authenticated
with check (user_id = (select auth.uid()) and created_at between now()-interval '1 minute' and now()+interval '1 minute');
create policy contact_read_admin on public.contact_messages for select to authenticated using(private.is_admin());
create index contact_user_time_idx on public.contact_messages(user_id,created_at desc);
create or replace function private.limit_contact() returns trigger language plpgsql security definer set search_path='' as $$
begin
  perform pg_advisory_xact_lock(hashtextextended(new.user_id::text,2));
  if (select count(*) from public.contact_messages where user_id=new.user_id and created_at > now()-interval '1 hour') >= 5 then
    raise exception 'Maximum 5 messages per hour' using errcode='22023';
  end if;
  return new;
end;
$$;
revoke all on function private.limit_contact() from public,anon,authenticated;
create trigger limit_contact before insert on public.contact_messages for each row execute function private.limit_contact();

-- Enforce the comparison limit even when a client bypasses the UI and RPC.
create or replace function private.limit_comparison() returns trigger language plpgsql security definer set search_path='' as $$
begin
  perform pg_advisory_xact_lock(hashtextextended(new.user_id::text,0));
  if not exists(select 1 from public.compare_items where user_id=new.user_id and deal_id=new.deal_id)
    and (select count(*) from public.compare_items where user_id=new.user_id) >= 4 then
    raise exception 'Maximum 4 compared offers' using errcode='22023';
  end if;
  return new;
end;
$$;
revoke all on function private.limit_comparison() from public,anon,authenticated;
create trigger limit_comparison before insert on public.compare_items for each row execute function private.limit_comparison();
notify pgrst,'reload schema';
