-- Application schema snapshot before Autopilot. New Supabase projects only. No personal data.
set check_function_bodies = off; set search_path = public, extensions;
create schema if not exists private; revoke all on schema private from public; grant usage on schema private to anon,authenticated,service_role;
create type public.ad_status as enum ('draft','active','paused','expired');
create type public.alert_status as enum ('active','triggered','paused','deleted');
create type public.deal_status as enum ('draft','active','paused','expired','archived');
create type public.stock_status as enum ('in_stock','limited','out_of_stock','unknown');
create type public.user_role as enum ('user','admin');
create table public.ad_slots (id bigint generated by default as identity not null,slug text not null,name text not null,location text not null,description text,is_active boolean default true not null,created_at timestamp with time zone default now() not null,updated_at timestamp with time zone default now() not null);
create table public.admin_audit_logs (id bigint generated by default as identity not null,admin_id uuid,action text not null,entity_type text,entity_id text,details jsonb default '{}'::jsonb not null,created_at timestamp with time zone default now() not null);
create table public.ads (id bigint generated by default as identity not null,slot_id bigint not null,advertiser_name text not null,title text,image_url text,destination_url text,status ad_status default 'draft'::ad_status not null,starts_at timestamp with time zone,ends_at timestamp with time zone,created_at timestamp with time zone default now() not null,updated_at timestamp with time zone default now() not null);
create table public.affiliate_clicks (id uuid default gen_random_uuid() not null,deal_id bigint,merchant_id bigint,user_id uuid,session_id text,source text,referrer text,clicked_at timestamp with time zone default now() not null);
create table public.categories (id bigint generated by default as identity not null,slug text not null,name_fr text not null,name_en text not null,description_fr text,description_en text,icon text,sort_order integer default 0 not null,is_active boolean default true not null,created_at timestamp with time zone default now() not null,updated_at timestamp with time zone default now() not null);
create table public.compare_items (user_id uuid not null,deal_id bigint not null,created_at timestamp with time zone default now() not null);
create table public.contact_messages (id bigint generated by default as identity not null,user_id uuid not null,name text not null,email text not null,message text not null,created_at timestamp with time zone default now() not null);
create table public.deals (id bigint generated by default as identity not null,merchant_id bigint,category_id bigint,external_id text,slug text not null,name text not null,description text,short_description text,image_url text,price numeric(14,2) not null,old_price numeric(14,2),currency text default 'MUR'::text not null,availability stock_status default 'unknown'::stock_status not null,original_url text,affiliate_url text,affiliate_network text,affiliate_program_id text,dealbot_score integer default 50 not null,score_price integer,score_discount integer,score_trust integer,score_freshness integer,status deal_status default 'draft'::deal_status not null,is_featured boolean default false not null,starts_at timestamp with time zone,expires_at timestamp with time zone,last_checked_at timestamp with time zone,created_at timestamp with time zone default now() not null,updated_at timestamp with time zone default now() not null);
create table public.favorites (user_id uuid not null,deal_id bigint not null,created_at timestamp with time zone default now() not null);
create table public.merchants (id bigint generated by default as identity not null,name text not null,slug text not null,website_url text,logo_url text,country_code text,affiliate_network text,affiliate_program_id text,external_id text,is_verified boolean default false not null,is_active boolean default true not null,created_at timestamp with time zone default now() not null,updated_at timestamp with time zone default now() not null);
create table public.price_alerts (id bigint generated by default as identity not null,user_id uuid not null,deal_id bigint not null,target_price numeric(14,2) not null,currency text default 'MUR'::text not null,status alert_status default 'active'::alert_status not null,triggered_at timestamp with time zone,created_at timestamp with time zone default now() not null,updated_at timestamp with time zone default now() not null);
create table public.price_history (id bigint generated by default as identity not null,deal_id bigint not null,price numeric(14,2) not null,old_price numeric(14,2),currency text default 'MUR'::text not null,availability stock_status default 'unknown'::stock_status not null,recorded_at timestamp with time zone default now() not null);
create table public.profiles (id uuid not null,full_name text,avatar_url text,role user_role default 'user'::user_role not null,preferred_language text default 'fr'::text not null,preferred_currency text default 'MUR'::text not null,created_at timestamp with time zone default now() not null,updated_at timestamp with time zone default now() not null);
create table public.site_settings (key text not null,value jsonb not null,description text,updated_by uuid,updated_at timestamp with time zone default now() not null);
CREATE OR REPLACE FUNCTION private.audit_catalog()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  insert into public.admin_audit_logs(admin_id, action, entity_type, entity_id, details)
  values(auth.uid(), lower(tg_op), tg_table_name, new.id::text,
    jsonb_build_object('status', to_jsonb(new)->>'status'));
  return new;
end;
$function$
;
CREATE OR REPLACE FUNCTION private.evaluate_alert()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare d public.deals;
begin
  select * into d from public.deals where id = new.deal_id;
  if d.id is null or d.status <> 'active' or (d.starts_at is not null and d.starts_at > now())
    or (d.expires_at is not null and d.expires_at <= now()) or new.currency <> d.currency then
    raise exception 'Offer unavailable or currency mismatch' using errcode = '22023';
  end if;
  new.status := case when d.price <= new.target_price and d.availability in ('in_stock','limited')
    then 'triggered'::public.alert_status else 'active'::public.alert_status end;
  new.triggered_at := case when new.status = 'triggered' then now() else null end;
  return new;
end;
$function$
;
CREATE OR REPLACE FUNCTION private.is_admin()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
  select auth.uid() is not null and exists (
    select 1 from public.profiles where id = (select auth.uid()) and role = 'admin'
  );
$function$
;
CREATE OR REPLACE FUNCTION private.limit_clicks()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  perform pg_advisory_xact_lock(hashtextextended(coalesce(new.user_id::text,new.session_id), 1));
  if (select count(*) from public.affiliate_clicks where session_id = new.session_id and clicked_at > now() - interval '1 minute') >= 30 then
    raise exception 'Too many clicks' using errcode = '22023';
  end if;
  return new;
end;
$function$
;
CREATE OR REPLACE FUNCTION private.limit_comparison()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  perform pg_advisory_xact_lock(hashtextextended(new.user_id::text,0));
  if not exists(select 1 from public.compare_items where user_id=new.user_id and deal_id=new.deal_id)
    and (select count(*) from public.compare_items where user_id=new.user_id) >= 4 then
    raise exception 'Maximum 4 compared offers' using errcode='22023';
  end if;
  return new;
end;
$function$
;
CREATE OR REPLACE FUNCTION private.limit_contact()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  perform pg_advisory_xact_lock(hashtextextended(new.user_id::text,2));
  if (select count(*) from public.contact_messages where user_id=new.user_id and created_at > now()-interval '1 hour') >= 5 then
    raise exception 'Maximum 5 messages per hour' using errcode='22023';
  end if;
  return new;
end;
$function$
;
CREATE OR REPLACE FUNCTION private.personal_snapshot()
 RETURNS jsonb
 LANGUAGE sql
 SET search_path TO ''
AS $function$
  select jsonb_build_object(
    'favorites',coalesce((select jsonb_agg(deal_id order by deal_id) from public.favorites where user_id=auth.uid()),'[]'::jsonb),
    'compare',coalesce((select jsonb_agg(deal_id order by deal_id) from public.compare_items where user_id=auth.uid()),'[]'::jsonb),
    'alerts',coalesce((select jsonb_agg(jsonb_build_object('id',id,'productId',deal_id,'targetPrice',target_price,'currency',currency,'status',status) order by deal_id)
      from public.price_alerts where user_id=auth.uid() and status::text<>'deleted'),'[]'::jsonb)
  );
$function$
;
CREATE OR REPLACE FUNCTION private.trigger_price_alerts()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  if new.status = 'active' and new.availability in ('in_stock','limited')
    and (new.starts_at is null or new.starts_at <= now()) and (new.expires_at is null or new.expires_at > now()) then
    update public.price_alerts set status = 'triggered', triggered_at = now()
    where deal_id = new.id and status = 'active' and currency = new.currency and target_price >= new.price;
  end if;
  return new;
end;
$function$
;
CREATE OR REPLACE FUNCTION public.admin_save_deal(payload jsonb)
 RETURNS bigint
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
declare
  merchant bigint; category bigint; offer bigint; existing public.deals;
  url text := nullif(trim(payload->>'url'),''); affiliate text; image text := nullif(trim(payload->>'imageUrl'),'');
  offer_status public.deal_status; starts timestamptz; expires timestamptz; featured boolean; link text;
  https_pattern constant text := '^https://([a-zA-Z0-9]([a-zA-Z0-9.-]*[a-zA-Z0-9])?|\[[0-9a-fA-F:]+\])(:[0-9]{1,5})?([/?#][^[:space:]]*)?$';
begin
  if not private.is_admin() then raise exception 'Admin required' using errcode='42501'; end if;
  if coalesce(payload->>'id','') <> '' then
    select * into existing from public.deals where id=(payload->>'id')::bigint for update;
    if not found then raise exception 'Offer not found' using errcode='22023'; end if;
  end if;
  affiliate := case when payload ? 'affiliateUrl' then nullif(trim(payload->>'affiliateUrl'),'') else existing.affiliate_url end;
  starts := case when payload ? 'startsAt' then nullif(payload->>'startsAt','')::timestamptz else existing.starts_at end;
  expires := nullif(payload->>'expiresAt','')::timestamptz;
  featured := case when payload ? 'featured' then coalesce((payload->>'featured')::boolean,false) else coalesce(existing.is_featured,false) end;
  offer_status := coalesce(payload->>'status','draft')::public.deal_status;
  if payload->>'name' is null or payload->>'store' is null
    or length(trim(payload->>'name')) not between 1 and 250 or length(trim(payload->>'store')) not between 1 and 150
    or (offer_status='active' and coalesce(affiliate,url) is null)
    or coalesce(payload->>'currency','MUR') not in ('MUR','EUR','USD','GBP')
    or (starts is not null and expires is not null and starts >= expires) then
    raise exception 'Invalid offer fields, publication dates or missing HTTPS merchant link' using errcode='22023';
  end if;
  foreach link in array array[url,affiliate,image] loop
    if link is not null and (link !~ https_pattern or position(chr(92) in link)>0) then
      raise exception 'Use a valid HTTPS URL without credentials or whitespace' using errcode='22023';
    end if;
  end loop;
  select id into category from public.categories where slug=payload->>'category' and is_active;
  if category is null then raise exception 'Unknown category' using errcode='22023'; end if;
  -- Editing a merchant's existing offer must not replace its identity/verification.
  if existing.merchant_id is not null then
    select id into merchant from public.merchants where id=existing.merchant_id
      and lower(trim(name))=lower(trim(payload->>'store'));
  end if;
  if merchant is null then
    insert into public.merchants(name,slug)
      values(trim(payload->>'store'),'merchant-'||md5(lower(trim(payload->>'store'))))
      on conflict(slug) do update set name=excluded.name returning id into merchant;
  end if;
  if existing.id is null then
    insert into public.deals(name,slug,merchant_id,category_id,price,old_price,currency,availability,description,
      original_url,affiliate_url,dealbot_score,status,image_url,starts_at,expires_at,is_featured)
    values(trim(payload->>'name'),'deal-'||gen_random_uuid()::text,merchant,category,(payload->>'price')::numeric,
      nullif(payload->>'oldPrice','')::numeric,coalesce(payload->>'currency','MUR'),(payload->>'availability')::public.stock_status,
      payload->>'description',url,affiliate,(payload->>'score')::int,offer_status,image,starts,expires,featured)
    returning id into offer;
  else
    update public.deals set name=trim(payload->>'name'),merchant_id=merchant,category_id=category,
      price=(payload->>'price')::numeric,old_price=nullif(payload->>'oldPrice','')::numeric,currency=coalesce(payload->>'currency','MUR'),
      availability=(payload->>'availability')::public.stock_status,description=payload->>'description',
      original_url=url,affiliate_url=affiliate,dealbot_score=(payload->>'score')::int,status=offer_status,image_url=image,
      starts_at=starts,expires_at=expires,is_featured=featured
    where id=existing.id returning id into offer;
  end if;
  return offer;
end;
$function$
;
CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  insert into public.profiles (
    id,
    full_name
  )
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', '')
  )
  on conflict (id) do nothing;

  return new;
end;
$function$
;
CREATE OR REPLACE FUNCTION public.is_admin()
 RETURNS boolean
 LANGUAGE sql
 STABLE
 SET search_path TO ''
AS $function$ select private.is_admin(); $function$
;
CREATE OR REPLACE FUNCTION public.record_deal_price()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  if tg_op='INSERT' or old.price is distinct from new.price
    or old.old_price is distinct from new.old_price
    or old.currency is distinct from new.currency
    or old.availability is distinct from new.availability then
    insert into public.price_history(deal_id,price,old_price,currency,availability)
    values(new.id,new.price,new.old_price,new.currency,new.availability);
  end if;
  return new;
end;
$function$
;
CREATE OR REPLACE FUNCTION public.save_personal_state(favorite_ids bigint[], comparison_ids bigint[], alerts jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
declare uid uuid := auth.uid();
begin
  if uid is null then raise exception 'Sign in required' using errcode = '42501'; end if;
  if favorite_ids is null or comparison_ids is null or alerts is null or jsonb_typeof(alerts) <> 'array'
    or cardinality(favorite_ids) > 500 or cardinality(comparison_ids) > 4 or jsonb_array_length(alerts) > 100 then
    raise exception 'Invalid collection size' using errcode = '22023';
  end if;
  perform pg_advisory_xact_lock(hashtextextended(uid::text, 0));
  delete from public.favorites where user_id = uid and not (deal_id = any(favorite_ids));
  insert into public.favorites (user_id, deal_id) select uid, unnest(favorite_ids) on conflict do nothing;
  delete from public.compare_items where user_id = uid and not (deal_id = any(comparison_ids));
  insert into public.compare_items (user_id, deal_id) select uid, unnest(comparison_ids) on conflict do nothing;
  delete from public.price_alerts where user_id = uid and deal_id not in
    (select (a->>'productId')::bigint from jsonb_array_elements(alerts) a);
  insert into public.price_alerts (user_id, deal_id, target_price, currency)
    select uid, (a->>'productId')::bigint, (a->>'targetPrice')::numeric, d.currency
    from jsonb_array_elements(alerts) a join public.deals d on d.id = (a->>'productId')::bigint
      and (a->>'currency' is null or a->>'currency' = d.currency)
  on conflict (user_id, deal_id) do update set target_price = excluded.target_price, currency = excluded.currency
    where price_alerts.target_price is distinct from excluded.target_price
      or price_alerts.currency is distinct from excluded.currency;
end;
$function$
;
CREATE OR REPLACE FUNCTION public.save_personal_state_checked(favorite_ids bigint[], comparison_ids bigint[], alerts jsonb, expected_state jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
declare current_state jsonb; field text; expected_values jsonb; current_values jsonb;
begin
  if auth.uid() is null then raise exception 'Sign in required' using errcode='42501'; end if;
  if expected_state is null or jsonb_typeof(expected_state)<>'object' then
    raise exception 'Expected account state required' using errcode='22023';
  end if;
  perform pg_advisory_xact_lock(hashtextextended(auth.uid()::text,0));
  current_state := private.personal_snapshot();
  foreach field in array array['favorites','compare','alerts'] loop
    if jsonb_typeof(expected_state->field) is distinct from 'array' then
      raise exception 'Invalid expected account state' using errcode='22023';
    end if;
    if field='alerts' then
      -- Server-generated IDs/status may change when a price falls; compare user choices only.
      select coalesce(jsonb_agg(jsonb_build_object('productId',(a->>'productId')::bigint,'targetPrice',(a->>'targetPrice')::numeric,'currency',a->>'currency') order by (a->>'productId')::bigint),'[]'::jsonb)
        into expected_values from jsonb_array_elements(expected_state->field) a;
      select coalesce(jsonb_agg(jsonb_build_object('productId',(a->>'productId')::bigint,'targetPrice',(a->>'targetPrice')::numeric,'currency',a->>'currency') order by (a->>'productId')::bigint),'[]'::jsonb)
        into current_values from jsonb_array_elements(current_state->field) a;
    else
      select coalesce(jsonb_agg(value::bigint order by value::bigint),'[]'::jsonb) into expected_values from jsonb_array_elements_text(expected_state->field);
      select coalesce(jsonb_agg(value::bigint order by value::bigint),'[]'::jsonb) into current_values from jsonb_array_elements_text(current_state->field);
    end if;
    if expected_values is distinct from current_values then
      raise exception 'Account changed on another device; reload before saving' using errcode='40001';
    end if;
  end loop;
  perform public.save_personal_state(favorite_ids,comparison_ids,alerts);
  return private.personal_snapshot();
end;
$function$
;
CREATE OR REPLACE FUNCTION public.set_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
begin
  new.updated_at = now();
  return new;
end;
$function$
;
CREATE OR REPLACE FUNCTION public.track_deal_click(offer_id bigint, browser_session text, page_source text)
 RETURNS text
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
declare d public.deals; destination text;
begin
  select * into d from public.deals where id = offer_id and status = 'active'
    and (starts_at is null or starts_at <= now()) and (expires_at is null or expires_at > now());
  destination := coalesce(nullif(d.affiliate_url,''), d.original_url);
  if destination is null or destination !~ '^https://[^/@[:space:]]+([/?#]|$)' then
    raise exception 'Merchant link unavailable' using errcode = '22023';
  end if;
  insert into public.affiliate_clicks(deal_id,merchant_id,user_id,session_id,source)
  values(d.id,d.merchant_id,auth.uid(),browser_session,page_source);
  return destination;
end;
$function$
;
alter table ad_slots add constraint ad_slots_pkey PRIMARY KEY (id);
alter table ad_slots add constraint ad_slots_slug_key UNIQUE (slug);
alter table admin_audit_logs add constraint admin_audit_logs_pkey PRIMARY KEY (id);
alter table ads add constraint ads_pkey PRIMARY KEY (id);
alter table affiliate_clicks add constraint affiliate_clicks_pkey PRIMARY KEY (id);
alter table categories add constraint categories_pkey PRIMARY KEY (id);
alter table categories add constraint categories_slug_key UNIQUE (slug);
alter table compare_items add constraint compare_items_pkey PRIMARY KEY (user_id, deal_id);
alter table contact_messages add constraint contact_messages_email_check CHECK (((length(email) >= 3) AND (length(email) <= 254)));
alter table contact_messages add constraint contact_messages_message_check CHECK (((length(message) >= 10) AND (length(message) <= 5000)));
alter table contact_messages add constraint contact_messages_name_check CHECK (((length(name) >= 1) AND (length(name) <= 150)));
alter table contact_messages add constraint contact_messages_pkey PRIMARY KEY (id);
alter table deals add constraint deals_check CHECK (((old_price IS NULL) OR (old_price >= price)));
alter table deals add constraint deals_dealbot_score_check CHECK (((dealbot_score >= 0) AND (dealbot_score <= 100)));
alter table deals add constraint deals_merchant_id_external_id_key UNIQUE (merchant_id, external_id);
alter table deals add constraint deals_pkey PRIMARY KEY (id);
alter table deals add constraint deals_price_check CHECK ((price >= (0)::numeric));
alter table deals add constraint deals_score_discount_check CHECK (((score_discount >= 0) AND (score_discount <= 100)));
alter table deals add constraint deals_score_freshness_check CHECK (((score_freshness >= 0) AND (score_freshness <= 100)));
alter table deals add constraint deals_score_price_check CHECK (((score_price >= 0) AND (score_price <= 100)));
alter table deals add constraint deals_score_trust_check CHECK (((score_trust >= 0) AND (score_trust <= 100)));
alter table deals add constraint deals_slug_key UNIQUE (slug);
alter table favorites add constraint favorites_pkey PRIMARY KEY (user_id, deal_id);
alter table merchants add constraint merchants_pkey PRIMARY KEY (id);
alter table merchants add constraint merchants_slug_key UNIQUE (slug);
alter table price_alerts add constraint price_alerts_pkey PRIMARY KEY (id);
alter table price_alerts add constraint price_alerts_target_price_check CHECK ((target_price > (0)::numeric));
alter table price_alerts add constraint price_alerts_user_id_deal_id_key UNIQUE (user_id, deal_id);
alter table price_history add constraint price_history_pkey PRIMARY KEY (id);
alter table price_history add constraint price_history_price_check CHECK ((price >= (0)::numeric));
alter table profiles add constraint profiles_pkey PRIMARY KEY (id);
alter table profiles add constraint profiles_preferred_language_check CHECK ((preferred_language = ANY (ARRAY['fr'::text, 'en'::text])));
alter table site_settings add constraint site_settings_pkey PRIMARY KEY (key);
alter table admin_audit_logs add constraint admin_audit_logs_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table ads add constraint ads_slot_id_fkey FOREIGN KEY (slot_id) REFERENCES ad_slots(id) ON DELETE CASCADE;
alter table affiliate_clicks add constraint affiliate_clicks_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES deals(id) ON DELETE SET NULL;
alter table affiliate_clicks add constraint affiliate_clicks_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES merchants(id) ON DELETE SET NULL;
alter table affiliate_clicks add constraint affiliate_clicks_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table compare_items add constraint compare_items_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES deals(id) ON DELETE CASCADE;
alter table compare_items add constraint compare_items_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table contact_messages add constraint contact_messages_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);
alter table deals add constraint deals_category_id_fkey FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL;
alter table deals add constraint deals_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES merchants(id) ON DELETE SET NULL;
alter table favorites add constraint favorites_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES deals(id) ON DELETE CASCADE;
alter table favorites add constraint favorites_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table price_alerts add constraint price_alerts_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES deals(id) ON DELETE CASCADE;
alter table price_alerts add constraint price_alerts_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table price_history add constraint price_history_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES deals(id) ON DELETE CASCADE;
alter table profiles add constraint profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table site_settings add constraint site_settings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL;
CREATE INDEX alerts_user_idx ON public.price_alerts USING btree (user_id);
CREATE INDEX alerts_active_idx ON public.price_alerts USING btree (deal_id, target_price) WHERE (status = 'active'::alert_status);
CREATE INDEX favorites_user_idx ON public.favorites USING btree (user_id);
CREATE INDEX compare_user_idx ON public.compare_items USING btree (user_id);
CREATE INDEX affiliate_click_deal_idx ON public.affiliate_clicks USING btree (deal_id, clicked_at DESC);
CREATE INDEX affiliate_click_merchant_idx ON public.affiliate_clicks USING btree (merchant_id, clicked_at DESC);
CREATE INDEX affiliate_click_user_idx ON public.affiliate_clicks USING btree (user_id, clicked_at DESC);
CREATE INDEX affiliate_click_session_time_idx ON public.affiliate_clicks USING btree (session_id, clicked_at DESC);
CREATE INDEX contact_user_time_idx ON public.contact_messages USING btree (user_id, created_at DESC);
CREATE INDEX deals_status_idx ON public.deals USING btree (status);
CREATE INDEX deals_category_idx ON public.deals USING btree (category_id);
CREATE INDEX deals_merchant_idx ON public.deals USING btree (merchant_id);
CREATE INDEX deals_price_idx ON public.deals USING btree (price);
CREATE INDEX deals_score_idx ON public.deals USING btree (dealbot_score DESC);
CREATE INDEX deals_featured_idx ON public.deals USING btree (is_featured) WHERE (is_featured = true);
CREATE INDEX deals_created_idx ON public.deals USING btree (created_at DESC);
CREATE INDEX deals_active_sort_idx ON public.deals USING btree (dealbot_score DESC, created_at DESC) WHERE (status = 'active'::deal_status);
CREATE INDEX price_history_deal_time_idx ON public.price_history USING btree (deal_id, recorded_at DESC);
CREATE TRIGGER profiles_updated_at BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER categories_updated_at BEFORE UPDATE ON public.categories FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER merchants_updated_at BEFORE UPDATE ON public.merchants FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER deals_updated_at BEFORE UPDATE ON public.deals FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER price_alerts_updated_at BEFORE UPDATE ON public.price_alerts FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER ad_slots_updated_at BEFORE UPDATE ON public.ad_slots FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER ads_updated_at BEFORE UPDATE ON public.ads FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION handle_new_user();
CREATE TRIGGER record_deal_price_history AFTER INSERT OR UPDATE ON public.deals FOR EACH ROW EXECUTE FUNCTION record_deal_price();
CREATE TRIGGER evaluate_price_alert BEFORE INSERT OR UPDATE OF target_price, deal_id, currency ON public.price_alerts FOR EACH ROW EXECUTE FUNCTION private.evaluate_alert();
CREATE TRIGGER trigger_price_alerts AFTER UPDATE OF price, availability, status ON public.deals FOR EACH ROW EXECUTE FUNCTION private.trigger_price_alerts();
CREATE TRIGGER audit_deal AFTER INSERT OR UPDATE ON public.deals FOR EACH ROW EXECUTE FUNCTION private.audit_catalog();
CREATE TRIGGER audit_merchant AFTER INSERT OR UPDATE ON public.merchants FOR EACH ROW EXECUTE FUNCTION private.audit_catalog();
CREATE TRIGGER limit_clicks BEFORE INSERT ON public.affiliate_clicks FOR EACH ROW EXECUTE FUNCTION private.limit_clicks();
CREATE TRIGGER limit_contact BEFORE INSERT ON public.contact_messages FOR EACH ROW EXECUTE FUNCTION private.limit_contact();
CREATE TRIGGER limit_comparison BEFORE INSERT ON public.compare_items FOR EACH ROW EXECUTE FUNCTION private.limit_comparison();
alter table public.price_alerts enable row level security;
alter table public.favorites enable row level security;
alter table public.compare_items enable row level security;
alter table public.affiliate_clicks enable row level security;
alter table public.categories enable row level security;
alter table public.merchants enable row level security;
alter table public.contact_messages enable row level security;
alter table public.deals enable row level security;
alter table public.price_history enable row level security;
alter table public.ad_slots enable row level security;
alter table public.ads enable row level security;
alter table public.site_settings enable row level security;
alter table public.admin_audit_logs enable row level security;
alter table public.profiles enable row level security;
create policy categories_public_read on public.categories as PERMISSIVE for SELECT to anon,authenticated using (((is_active = true) OR is_admin()));
create policy merchants_public_read on public.merchants as PERMISSIVE for SELECT to anon,authenticated using (((is_active = true) OR is_admin()));
create policy price_history_public_read on public.price_history as PERMISSIVE for SELECT to anon,authenticated using (((EXISTS ( SELECT 1
   FROM deals d
  WHERE ((d.id = price_history.deal_id) AND (d.status = 'active'::deal_status)))) OR is_admin()));
create policy ad_slots_public_read on public.ad_slots as PERMISSIVE for SELECT to anon,authenticated using (((is_active = true) OR is_admin()));
create policy ads_public_read on public.ads as PERMISSIVE for SELECT to anon,authenticated using ((((status = 'active'::ad_status) AND ((starts_at IS NULL) OR (starts_at <= now())) AND ((ends_at IS NULL) OR (ends_at >= now()))) OR is_admin()));
create policy profiles_read_own on public.profiles as PERMISSIVE for SELECT to authenticated using (((id = ( SELECT auth.uid() AS uid)) OR is_admin()));
create policy favorites_read_own on public.favorites as PERMISSIVE for SELECT to authenticated using ((user_id = ( SELECT auth.uid() AS uid)));
create policy favorites_insert_own on public.favorites as PERMISSIVE for INSERT to authenticated with check ((user_id = ( SELECT auth.uid() AS uid)));
create policy favorites_delete_own on public.favorites as PERMISSIVE for DELETE to authenticated using ((user_id = ( SELECT auth.uid() AS uid)));
create policy compare_read_own on public.compare_items as PERMISSIVE for SELECT to authenticated using ((user_id = ( SELECT auth.uid() AS uid)));
create policy compare_insert_own on public.compare_items as PERMISSIVE for INSERT to authenticated with check ((user_id = ( SELECT auth.uid() AS uid)));
create policy compare_delete_own on public.compare_items as PERMISSIVE for DELETE to authenticated using ((user_id = ( SELECT auth.uid() AS uid)));
create policy alerts_read_own on public.price_alerts as PERMISSIVE for SELECT to authenticated using ((user_id = ( SELECT auth.uid() AS uid)));
create policy alerts_insert_own on public.price_alerts as PERMISSIVE for INSERT to authenticated with check ((user_id = ( SELECT auth.uid() AS uid)));
create policy alerts_update_own on public.price_alerts as PERMISSIVE for UPDATE to authenticated using ((user_id = ( SELECT auth.uid() AS uid))) with check ((user_id = ( SELECT auth.uid() AS uid)));
create policy alerts_delete_own on public.price_alerts as PERMISSIVE for DELETE to authenticated using ((user_id = ( SELECT auth.uid() AS uid)));
create policy categories_admin_all on public.categories as PERMISSIVE for ALL to authenticated using (is_admin()) with check (is_admin());
create policy merchants_admin_all on public.merchants as PERMISSIVE for ALL to authenticated using (is_admin()) with check (is_admin());
create policy deals_admin_all on public.deals as PERMISSIVE for ALL to authenticated using (is_admin()) with check (is_admin());
create policy price_history_admin_all on public.price_history as PERMISSIVE for ALL to authenticated using (is_admin()) with check (is_admin());
create policy ad_slots_admin_all on public.ad_slots as PERMISSIVE for ALL to authenticated using (is_admin()) with check (is_admin());
create policy ads_admin_all on public.ads as PERMISSIVE for ALL to authenticated using (is_admin()) with check (is_admin());
create policy affiliate_clicks_admin_read on public.affiliate_clicks as PERMISSIVE for SELECT to authenticated using (is_admin());
create policy audit_admin_read on public.admin_audit_logs as PERMISSIVE for SELECT to authenticated using (is_admin());
create policy audit_admin_insert on public.admin_audit_logs as PERMISSIVE for INSERT to authenticated with check ((is_admin() AND (admin_id = ( SELECT auth.uid() AS uid))));
create policy settings_admin_all on public.site_settings as PERMISSIVE for ALL to authenticated using (is_admin()) with check (is_admin());
create policy profiles_update_own on public.profiles as PERMISSIVE for UPDATE to authenticated using ((id = ( SELECT auth.uid() AS uid))) with check ((id = ( SELECT auth.uid() AS uid)));
create policy deals_public_read on public.deals as PERMISSIVE for SELECT to anon,authenticated using ((private.is_admin() OR ((status = 'active'::deal_status) AND ((starts_at IS NULL) OR (starts_at <= now())) AND ((expires_at IS NULL) OR (expires_at > now())))));
create policy affiliate_click_public_insert on public.affiliate_clicks as PERMISSIVE for INSERT to anon,authenticated with check (((NOT (user_id IS DISTINCT FROM ( SELECT auth.uid() AS uid))) AND ((length(session_id) >= 16) AND (length(session_id) <= 80)) AND (source = ANY (ARRAY['home'::text, 'explore'::text, 'deal'::text, 'compare'::text, 'favorites'::text, 'intelligence'::text])) AND (referrer IS NULL) AND ((clicked_at >= (now() - '00:01:00'::interval)) AND (clicked_at <= (now() + '00:01:00'::interval))) AND (EXISTS ( SELECT 1
   FROM deals d
  WHERE ((d.id = affiliate_clicks.deal_id) AND (d.merchant_id = affiliate_clicks.merchant_id) AND (d.status = 'active'::deal_status) AND ((d.starts_at IS NULL) OR (d.starts_at <= now())) AND ((d.expires_at IS NULL) OR (d.expires_at > now())))))));
create policy contact_insert_own on public.contact_messages as PERMISSIVE for INSERT to authenticated with check (((user_id = ( SELECT auth.uid() AS uid)) AND ((created_at >= (now() - '00:01:00'::interval)) AND (created_at <= (now() + '00:01:00'::interval)))));
create policy contact_read_admin on public.contact_messages as PERMISSIVE for SELECT to authenticated using (private.is_admin());
revoke all on all tables in schema public from anon,authenticated,service_role;
revoke all on all sequences in schema public from anon,authenticated,service_role;
revoke all on all functions in schema public from public,anon,authenticated,service_role;
revoke all on all functions in schema private from public,anon,authenticated,service_role;
grant INSERT on table public.price_alerts to anon;
grant SELECT on table public.price_alerts to anon;
grant UPDATE on table public.price_alerts to anon;
grant DELETE on table public.price_alerts to anon;
grant INSERT on table public.price_alerts to authenticated;
grant SELECT on table public.price_alerts to authenticated;
grant DELETE on table public.price_alerts to authenticated;
grant INSERT on table public.price_alerts to service_role;
grant SELECT on table public.price_alerts to service_role;
grant UPDATE on table public.price_alerts to service_role;
grant DELETE on table public.price_alerts to service_role;
grant TRUNCATE on table public.price_alerts to service_role;
grant REFERENCES on table public.price_alerts to service_role;
grant TRIGGER on table public.price_alerts to service_role;
grant INSERT on table public.favorites to anon;
grant SELECT on table public.favorites to anon;
grant UPDATE on table public.favorites to anon;
grant DELETE on table public.favorites to anon;
grant INSERT on table public.favorites to authenticated;
grant SELECT on table public.favorites to authenticated;
grant UPDATE on table public.favorites to authenticated;
grant DELETE on table public.favorites to authenticated;
grant INSERT on table public.favorites to service_role;
grant SELECT on table public.favorites to service_role;
grant UPDATE on table public.favorites to service_role;
grant DELETE on table public.favorites to service_role;
grant TRUNCATE on table public.favorites to service_role;
grant REFERENCES on table public.favorites to service_role;
grant TRIGGER on table public.favorites to service_role;
grant INSERT on table public.compare_items to anon;
grant SELECT on table public.compare_items to anon;
grant UPDATE on table public.compare_items to anon;
grant DELETE on table public.compare_items to anon;
grant INSERT on table public.compare_items to authenticated;
grant SELECT on table public.compare_items to authenticated;
grant UPDATE on table public.compare_items to authenticated;
grant DELETE on table public.compare_items to authenticated;
grant INSERT on table public.compare_items to service_role;
grant SELECT on table public.compare_items to service_role;
grant UPDATE on table public.compare_items to service_role;
grant DELETE on table public.compare_items to service_role;
grant TRUNCATE on table public.compare_items to service_role;
grant REFERENCES on table public.compare_items to service_role;
grant TRIGGER on table public.compare_items to service_role;
grant INSERT on table public.affiliate_clicks to anon;
grant SELECT on table public.affiliate_clicks to anon;
grant UPDATE on table public.affiliate_clicks to anon;
grant DELETE on table public.affiliate_clicks to anon;
grant INSERT on table public.affiliate_clicks to authenticated;
grant SELECT on table public.affiliate_clicks to authenticated;
grant UPDATE on table public.affiliate_clicks to authenticated;
grant DELETE on table public.affiliate_clicks to authenticated;
grant INSERT on table public.affiliate_clicks to service_role;
grant SELECT on table public.affiliate_clicks to service_role;
grant UPDATE on table public.affiliate_clicks to service_role;
grant DELETE on table public.affiliate_clicks to service_role;
grant TRUNCATE on table public.affiliate_clicks to service_role;
grant REFERENCES on table public.affiliate_clicks to service_role;
grant TRIGGER on table public.affiliate_clicks to service_role;
grant INSERT on table public.categories to anon;
grant SELECT on table public.categories to anon;
grant UPDATE on table public.categories to anon;
grant DELETE on table public.categories to anon;
grant INSERT on table public.categories to authenticated;
grant SELECT on table public.categories to authenticated;
grant UPDATE on table public.categories to authenticated;
grant DELETE on table public.categories to authenticated;
grant INSERT on table public.categories to service_role;
grant SELECT on table public.categories to service_role;
grant UPDATE on table public.categories to service_role;
grant DELETE on table public.categories to service_role;
grant TRUNCATE on table public.categories to service_role;
grant REFERENCES on table public.categories to service_role;
grant TRIGGER on table public.categories to service_role;
grant INSERT on table public.merchants to anon;
grant SELECT on table public.merchants to anon;
grant UPDATE on table public.merchants to anon;
grant DELETE on table public.merchants to anon;
grant INSERT on table public.merchants to authenticated;
grant SELECT on table public.merchants to authenticated;
grant UPDATE on table public.merchants to authenticated;
grant DELETE on table public.merchants to authenticated;
grant INSERT on table public.merchants to service_role;
grant SELECT on table public.merchants to service_role;
grant UPDATE on table public.merchants to service_role;
grant DELETE on table public.merchants to service_role;
grant TRUNCATE on table public.merchants to service_role;
grant REFERENCES on table public.merchants to service_role;
grant TRIGGER on table public.merchants to service_role;
grant INSERT on table public.contact_messages to service_role;
grant SELECT on table public.contact_messages to service_role;
grant UPDATE on table public.contact_messages to service_role;
grant DELETE on table public.contact_messages to service_role;
grant TRUNCATE on table public.contact_messages to service_role;
grant REFERENCES on table public.contact_messages to service_role;
grant TRIGGER on table public.contact_messages to service_role;
grant INSERT on table public.contact_messages to authenticated;
grant SELECT on table public.contact_messages to authenticated;
grant INSERT on table public.deals to anon;
grant SELECT on table public.deals to anon;
grant UPDATE on table public.deals to anon;
grant DELETE on table public.deals to anon;
grant INSERT on table public.deals to authenticated;
grant SELECT on table public.deals to authenticated;
grant UPDATE on table public.deals to authenticated;
grant DELETE on table public.deals to authenticated;
grant INSERT on table public.deals to service_role;
grant SELECT on table public.deals to service_role;
grant UPDATE on table public.deals to service_role;
grant DELETE on table public.deals to service_role;
grant TRUNCATE on table public.deals to service_role;
grant REFERENCES on table public.deals to service_role;
grant TRIGGER on table public.deals to service_role;
grant INSERT on table public.price_history to anon;
grant SELECT on table public.price_history to anon;
grant UPDATE on table public.price_history to anon;
grant DELETE on table public.price_history to anon;
grant INSERT on table public.price_history to authenticated;
grant SELECT on table public.price_history to authenticated;
grant UPDATE on table public.price_history to authenticated;
grant DELETE on table public.price_history to authenticated;
grant INSERT on table public.price_history to service_role;
grant SELECT on table public.price_history to service_role;
grant UPDATE on table public.price_history to service_role;
grant DELETE on table public.price_history to service_role;
grant TRUNCATE on table public.price_history to service_role;
grant REFERENCES on table public.price_history to service_role;
grant TRIGGER on table public.price_history to service_role;
grant INSERT on table public.ad_slots to anon;
grant SELECT on table public.ad_slots to anon;
grant UPDATE on table public.ad_slots to anon;
grant DELETE on table public.ad_slots to anon;
grant INSERT on table public.ad_slots to authenticated;
grant SELECT on table public.ad_slots to authenticated;
grant UPDATE on table public.ad_slots to authenticated;
grant DELETE on table public.ad_slots to authenticated;
grant INSERT on table public.ad_slots to service_role;
grant SELECT on table public.ad_slots to service_role;
grant UPDATE on table public.ad_slots to service_role;
grant DELETE on table public.ad_slots to service_role;
grant TRUNCATE on table public.ad_slots to service_role;
grant REFERENCES on table public.ad_slots to service_role;
grant TRIGGER on table public.ad_slots to service_role;
grant INSERT on table public.ads to anon;
grant SELECT on table public.ads to anon;
grant UPDATE on table public.ads to anon;
grant DELETE on table public.ads to anon;
grant INSERT on table public.ads to authenticated;
grant SELECT on table public.ads to authenticated;
grant UPDATE on table public.ads to authenticated;
grant DELETE on table public.ads to authenticated;
grant INSERT on table public.ads to service_role;
grant SELECT on table public.ads to service_role;
grant UPDATE on table public.ads to service_role;
grant DELETE on table public.ads to service_role;
grant TRUNCATE on table public.ads to service_role;
grant REFERENCES on table public.ads to service_role;
grant TRIGGER on table public.ads to service_role;
grant INSERT on table public.site_settings to anon;
grant SELECT on table public.site_settings to anon;
grant UPDATE on table public.site_settings to anon;
grant DELETE on table public.site_settings to anon;
grant INSERT on table public.site_settings to authenticated;
grant SELECT on table public.site_settings to authenticated;
grant UPDATE on table public.site_settings to authenticated;
grant DELETE on table public.site_settings to authenticated;
grant INSERT on table public.site_settings to service_role;
grant SELECT on table public.site_settings to service_role;
grant UPDATE on table public.site_settings to service_role;
grant DELETE on table public.site_settings to service_role;
grant TRUNCATE on table public.site_settings to service_role;
grant REFERENCES on table public.site_settings to service_role;
grant TRIGGER on table public.site_settings to service_role;
grant INSERT on table public.admin_audit_logs to anon;
grant SELECT on table public.admin_audit_logs to anon;
grant UPDATE on table public.admin_audit_logs to anon;
grant DELETE on table public.admin_audit_logs to anon;
grant INSERT on table public.admin_audit_logs to authenticated;
grant SELECT on table public.admin_audit_logs to authenticated;
grant UPDATE on table public.admin_audit_logs to authenticated;
grant DELETE on table public.admin_audit_logs to authenticated;
grant INSERT on table public.admin_audit_logs to service_role;
grant SELECT on table public.admin_audit_logs to service_role;
grant UPDATE on table public.admin_audit_logs to service_role;
grant DELETE on table public.admin_audit_logs to service_role;
grant TRUNCATE on table public.admin_audit_logs to service_role;
grant REFERENCES on table public.admin_audit_logs to service_role;
grant TRIGGER on table public.admin_audit_logs to service_role;
grant SELECT on table public.profiles to authenticated;
grant INSERT on table public.profiles to service_role;
grant SELECT on table public.profiles to service_role;
grant UPDATE on table public.profiles to service_role;
grant DELETE on table public.profiles to service_role;
grant TRUNCATE on table public.profiles to service_role;
grant REFERENCES on table public.profiles to service_role;
grant TRIGGER on table public.profiles to service_role;
grant UPDATE (avatar_url) on public.profiles to authenticated;
grant UPDATE (full_name) on public.profiles to authenticated;
grant UPDATE (preferred_currency) on public.profiles to authenticated;
grant UPDATE (preferred_language) on public.profiles to authenticated;
grant UPDATE (avatar_url) on public.profiles to service_role;
grant UPDATE (created_at) on public.profiles to service_role;
grant UPDATE (full_name) on public.profiles to service_role;
grant UPDATE (id) on public.profiles to service_role;
grant UPDATE (preferred_currency) on public.profiles to service_role;
grant UPDATE (preferred_language) on public.profiles to service_role;
grant UPDATE (role) on public.profiles to service_role;
grant UPDATE (updated_at) on public.profiles to service_role;
grant EXECUTE on function is_admin() to service_role;
grant EXECUTE on function is_admin() to authenticated;
grant EXECUTE on function is_admin() to anon;
grant EXECUTE on function record_deal_price() to service_role;
grant EXECUTE on function set_updated_at() to public;
grant EXECUTE on function set_updated_at() to anon;
grant EXECUTE on function set_updated_at() to authenticated;
grant EXECUTE on function set_updated_at() to service_role;
grant EXECUTE on function handle_new_user() to service_role;
grant EXECUTE on function private.is_admin() to anon;
grant EXECUTE on function private.is_admin() to authenticated;
grant EXECUTE on function track_deal_click(bigint,text,text) to anon;
grant EXECUTE on function track_deal_click(bigint,text,text) to authenticated;
grant EXECUTE on function track_deal_click(bigint,text,text) to service_role;
grant EXECUTE on function save_personal_state(bigint[],bigint[],jsonb) to authenticated;
grant EXECUTE on function save_personal_state(bigint[],bigint[],jsonb) to service_role;
grant EXECUTE on function admin_save_deal(jsonb) to authenticated;
grant EXECUTE on function admin_save_deal(jsonb) to service_role;
grant EXECUTE on function private.personal_snapshot() to authenticated;
grant EXECUTE on function save_personal_state_checked(bigint[],bigint[],jsonb,jsonb) to authenticated;
grant EXECUTE on function save_personal_state_checked(bigint[],bigint[],jsonb,jsonb) to service_role;
grant SELECT on sequence categories_id_seq to anon;
grant UPDATE on sequence categories_id_seq to anon;
grant USAGE on sequence categories_id_seq to anon;
grant SELECT on sequence categories_id_seq to authenticated;
grant UPDATE on sequence categories_id_seq to authenticated;
grant USAGE on sequence categories_id_seq to authenticated;
grant SELECT on sequence categories_id_seq to service_role;
grant UPDATE on sequence categories_id_seq to service_role;
grant USAGE on sequence categories_id_seq to service_role;
grant SELECT on sequence merchants_id_seq to anon;
grant UPDATE on sequence merchants_id_seq to anon;
grant USAGE on sequence merchants_id_seq to anon;
grant SELECT on sequence merchants_id_seq to authenticated;
grant UPDATE on sequence merchants_id_seq to authenticated;
grant USAGE on sequence merchants_id_seq to authenticated;
grant SELECT on sequence merchants_id_seq to service_role;
grant UPDATE on sequence merchants_id_seq to service_role;
grant USAGE on sequence merchants_id_seq to service_role;
grant SELECT on sequence deals_id_seq to anon;
grant UPDATE on sequence deals_id_seq to anon;
grant USAGE on sequence deals_id_seq to anon;
grant SELECT on sequence deals_id_seq to authenticated;
grant UPDATE on sequence deals_id_seq to authenticated;
grant USAGE on sequence deals_id_seq to authenticated;
grant SELECT on sequence deals_id_seq to service_role;
grant UPDATE on sequence deals_id_seq to service_role;
grant USAGE on sequence deals_id_seq to service_role;
grant SELECT on sequence price_history_id_seq to anon;
grant UPDATE on sequence price_history_id_seq to anon;
grant USAGE on sequence price_history_id_seq to anon;
grant SELECT on sequence price_history_id_seq to authenticated;
grant UPDATE on sequence price_history_id_seq to authenticated;
grant USAGE on sequence price_history_id_seq to authenticated;
grant SELECT on sequence price_history_id_seq to service_role;
grant UPDATE on sequence price_history_id_seq to service_role;
grant USAGE on sequence price_history_id_seq to service_role;
grant SELECT on sequence price_alerts_id_seq to anon;
grant UPDATE on sequence price_alerts_id_seq to anon;
grant USAGE on sequence price_alerts_id_seq to anon;
grant SELECT on sequence price_alerts_id_seq to authenticated;
grant UPDATE on sequence price_alerts_id_seq to authenticated;
grant USAGE on sequence price_alerts_id_seq to authenticated;
grant SELECT on sequence price_alerts_id_seq to service_role;
grant UPDATE on sequence price_alerts_id_seq to service_role;
grant USAGE on sequence price_alerts_id_seq to service_role;
grant SELECT on sequence ad_slots_id_seq to anon;
grant UPDATE on sequence ad_slots_id_seq to anon;
grant USAGE on sequence ad_slots_id_seq to anon;
grant SELECT on sequence ad_slots_id_seq to authenticated;
grant UPDATE on sequence ad_slots_id_seq to authenticated;
grant USAGE on sequence ad_slots_id_seq to authenticated;
grant SELECT on sequence ad_slots_id_seq to service_role;
grant UPDATE on sequence ad_slots_id_seq to service_role;
grant USAGE on sequence ad_slots_id_seq to service_role;
grant SELECT on sequence ads_id_seq to anon;
grant UPDATE on sequence ads_id_seq to anon;
grant USAGE on sequence ads_id_seq to anon;
grant SELECT on sequence ads_id_seq to authenticated;
grant UPDATE on sequence ads_id_seq to authenticated;
grant USAGE on sequence ads_id_seq to authenticated;
grant SELECT on sequence ads_id_seq to service_role;
grant UPDATE on sequence ads_id_seq to service_role;
grant USAGE on sequence ads_id_seq to service_role;
grant SELECT on sequence admin_audit_logs_id_seq to anon;
grant UPDATE on sequence admin_audit_logs_id_seq to anon;
grant USAGE on sequence admin_audit_logs_id_seq to anon;
grant SELECT on sequence admin_audit_logs_id_seq to authenticated;
grant UPDATE on sequence admin_audit_logs_id_seq to authenticated;
grant USAGE on sequence admin_audit_logs_id_seq to authenticated;
grant SELECT on sequence admin_audit_logs_id_seq to service_role;
grant UPDATE on sequence admin_audit_logs_id_seq to service_role;
grant USAGE on sequence admin_audit_logs_id_seq to service_role;
grant SELECT on sequence contact_messages_id_seq to anon;
grant UPDATE on sequence contact_messages_id_seq to anon;
grant USAGE on sequence contact_messages_id_seq to anon;
grant SELECT on sequence contact_messages_id_seq to authenticated;
grant UPDATE on sequence contact_messages_id_seq to authenticated;
grant USAGE on sequence contact_messages_id_seq to authenticated;
grant SELECT on sequence contact_messages_id_seq to service_role;
grant UPDATE on sequence contact_messages_id_seq to service_role;
grant USAGE on sequence contact_messages_id_seq to service_role;
grant update(target_price,currency) on public.price_alerts to authenticated;
set check_function_bodies = on;
